from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from flightApp.models import Flight

class FlightAuthTests(APITestCase):

    def setUp(self):
        # 1. Create a user
        self.username = "testuser"
        self.password = "testpass123"
        self.user = User.objects.create_user(username=self.username, password=self.password)
        
        # 2. Define URLs
        self.login_url = reverse('api=token-auth') # Matches your urls.py name
        self.flights_url = '/flights/'

    def test_token_generation_on_signup(self):
        """
        TC-01: Verify that your signal in models.py 
        automatically created a token for the new user.
        """
        token = Token.objects.filter(user=self.user).first()
        self.assertIsNotNone(token)

    def test_login_returns_token(self):
        """
        TC-03: Verify successful login returns a token string.
        """
        data = {
            "username": self.username,
            "password": self.password
        }
        response = self.client.post(self.login_url, data)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn('token', response.data)

    def test_access_flights_without_token_fails(self):
        """
        TC-06: Verify that IsAuthenticated blocks anonymous requests.
        """
        response = self.client.get(self.flights_url)
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_access_flights_with_token_succeeds(self):
        """
        TC-07: Verify that providing the Token header allows access.
        """
        # Fetch the token generated by your signal
        token = Token.objects.get(user__username=self.username)
        
        # Set the Authorization header
        self.client.credentials(HTTP_AUTHORIZATION='Token ' + token.key)
        
        response = self.client.get(self.flights_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_login_with_invalid_credentials(self):
        """
        TC-04: Verify that wrong passwords return an error.
        """
        data = {
            "username": self.username,
            "password": "wrongpassword"
        }
        response = self.client.post(self.login_url, data)
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)