# Generated by Django 5.2.3 on 2025-07-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrivaleCity',
            new_name='arrivalCity',
        ),
    ]
