# Generated by Django 5.2.3 on 2025-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureCity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
